spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db?useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8086
application:
  app:
    jwtSecrect: heeheeh